version: "3.8"
services:
  mongo-db:
    image: mongo

  api-gateway:
    image: jeffreyfontys/collecticats-api-gateway:main
    ports:
      - 8080:8080
  
  user-service:
    image: jeffreyfontys/collecticats-user-service:main
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-db

  cat-service:
    image: jeffreyfontys/collecticats-cat-service:main
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-db

  discovery-server:
    image: jeffreyfontys/collecticats-discovery-server:main
    ports:
      - 8761:8761
