version: "3.8"

services:

  mongo-db:
    image: mongo
    volumes:
      - db:/data/db

  api-gateway:
    image: jeffreyfontys/collecticats-api-gateway:main
    ports:
      - ${GATEWAY_PORT:-8080}:8080
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka
  
  user-service:
    image: jeffreyfontys/collecticats-user-service:main
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db/user
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka

  cat-service:
    image: jeffreyfontys/collecticats-cat-service:main
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db/cat
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka

  discovery-server:
    image: jeffreyfontys/collecticats-discovery-server:main
    ports:
      - ${EUREKA_PORT:-8761}:8761

volumes:
  db:
